// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh8u-clqNaMk71dNhoiYFVPZhBtAsqJsA',
    appId: '1:822765454061:web:f2aff174e23fb37a11c2e4',
    messagingSenderId: '822765454061',
    projectId: 'ica14-54eb1',
    authDomain: 'ica14-54eb1.firebaseapp.com',
    storageBucket: 'ica14-54eb1.firebasestorage.app',
    measurementId: 'G-PFZWEM063N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo36mZC0l1cqVEb98vWVtMmqqnwfOQuhY',
    appId: '1:822765454061:android:626eaf6d32b52d9f11c2e4',
    messagingSenderId: '822765454061',
    projectId: 'ica14-54eb1',
    storageBucket: 'ica14-54eb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQkWGPYabK_-qL1xf2FijQo-W2TpMil_4',
    appId: '1:822765454061:ios:e5764f6dd21a9b5411c2e4',
    messagingSenderId: '822765454061',
    projectId: 'ica14-54eb1',
    storageBucket: 'ica14-54eb1.firebasestorage.app',
    iosBundleId: 'com.example.ica14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQkWGPYabK_-qL1xf2FijQo-W2TpMil_4',
    appId: '1:822765454061:ios:e5764f6dd21a9b5411c2e4',
    messagingSenderId: '822765454061',
    projectId: 'ica14-54eb1',
    storageBucket: 'ica14-54eb1.firebasestorage.app',
    iosBundleId: 'com.example.ica14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh8u-clqNaMk71dNhoiYFVPZhBtAsqJsA',
    appId: '1:822765454061:web:82e624203dbc38b811c2e4',
    messagingSenderId: '822765454061',
    projectId: 'ica14-54eb1',
    authDomain: 'ica14-54eb1.firebaseapp.com',
    storageBucket: 'ica14-54eb1.firebasestorage.app',
    measurementId: 'G-Y7H9CJD56R',
  );
}
